import assert from 'node:assert/strict';
import test from 'node:test';
import {architectureSchema,emptyArchitecture,architectureIssues,deriveArchitecturalRooms,wallPolygon,wallRuns,roomMetrics,formatArchitectureLength} from '../src/lib/imo3d/architecture';
import type {ArchitecturalWall,Architecture} from '../src/lib/imo3d/architecture';
const wall=(id:string,x:number,z:number,x2:number,z2:number):ArchitecturalWall=>({id,a:{x,z},b:{x:x2,z:z2},thickness:.2,height:3,kind:'partition',confidence:.9,source:'manual',evidenceIds:[]});
function box():Architecture{return {...emptyArchitecture(0),walls:[wall('a',0,0,6,0),wall('b',6,0,6,4),wall('c',6,4,0,4),wall('d',0,4,0,0)]};}
test('closed walls produce one bounded face; missing walls and cameras cannot invent one',()=>{const m=box(),r=deriveArchitecturalRooms(m);assert.equal(r.length,1);assert.ok(Math.abs(roomMetrics(r[0]).area-22.04)<1e-8);assert.ok(Math.abs(roomMetrics(r[0]).perimeter-19.2)<1e-8);assert.deepEqual(deriveArchitecturalRooms(emptyArchitecture(0)),[]);m.walls.pop();assert.deepEqual(deriveArchitecturalRooms(m),[]);});
test('split shared partition produces two rooms without an exterior duplicate',()=>{const m=box();m.walls=[wall('a',0,0,3,0),wall('aa',3,0,6,0),wall('b',6,0,6,4),wall('c',6,4,3,4),wall('cc',3,4,0,4),wall('d',0,4,0,0),wall('p',3,0,3,4)];const rooms=deriveArchitecturalRooms(m);assert.equal(rooms.length,2);assert.ok(rooms.every(r=>Math.abs(roomMetrics(r).area-10.64)<1e-8));});
test('unknown thickness and unsplit junctions cannot produce verified rooms',()=>{const m=box();m.walls[0].thickness=null;assert.deepEqual(deriveArchitecturalRooms(m),[]);assert.deepEqual(wallPolygon(m.walls[0]),[]);assert.deepEqual(wallRuns(m,m.walls[0]),[]);m.walls[0].thickness=.2;m.walls.push(wall('p',3,0,3,4));assert.ok(architectureIssues(m).some(i=>i.code==='unsplit-junction'));assert.deepEqual(deriveArchitecturalRooms(m),[]);});
test('wall apertures retain lintels; conflicting cuts fail closed',()=>{const m=box();m.openings=[{id:'door',wallId:'a',kind:'door',offset:1,width:1,height:2,sillHeight:0,hinge:null,swing:null,confidence:1,source:'manual'}];const runs=wallRuns(m,m.walls[0]);assert.ok(runs.some(r=>r.a.x===1&&r.b.x===2&&r.bottom===2&&r.top===3));assert.ok(!runs.some(r=>r.a.x===1&&r.bottom===0));m.openings.push({...m.openings[0],id:'other',offset:1.5});assert.ok(architectureIssues(m).some(i=>i.code==='overlapping-openings'));assert.deepEqual(wallRuns(m,m.walls[0]),[]);});
test('host, duplicate and calibration errors are diagnosed',()=>{const m=box();m.scale.status='calibrated';m.openings=[{id:'a',wallId:'absent',kind:'door',offset:1,width:1,height:2,sillHeight:0,hinge:null,swing:null,confidence:1,source:'manual'}];const codes=architectureIssues(m).map(i=>i.code);for(const code of ['scale','duplicate-id','missing-host'])assert.ok(codes.includes(code));});
test('self crossing polygons and camera collisions are diagnosed',()=>{const m=box();m.rooms=[{id:'r',name:'r',polygon:[{x:0,z:0},{x:6,z:4},{x:0,z:4},{x:6,z:0}],wallIds:[],cameraIds:[],confidence:1}];assert.ok(architectureIssues(m).some(i=>i.code==='invalid-room'));m.rooms=deriveArchitecturalRooms({...m,rooms:[]});const codes=architectureIssues(m,[{id:'outside',position:{x:10,z:10}},{id:'wall',position:{x:3,z:0}}]).map(i=>i.code);assert.ok(codes.includes('camera-outside'));assert.ok(codes.includes('camera-on-wall'));});
test('schema and formatting prevent negative thickness and uncalibrated metric labels',()=>{assert.equal(architectureSchema.safeParse({...box(),walls:[{...box().walls[0],thickness:-1}]}).success,false);assert.equal(formatArchitectureLength(5,emptyArchitecture(0).scale),'غير معاير');assert.equal(formatArchitectureLength(5,{status:'calibrated',metersPerUnit:.1,displayUnit:'mm'}),'500 mm');});

test('insets preserve oblique walls and reject rooms narrower than their wall thickness',()=>{const m=box();m.walls=[wall('a',0,0,6,0),wall('b',6,0,5,4),wall('c',5,4,0,4),wall('d',0,4,0,0)];const r=deriveArchitecturalRooms(m);assert.equal(r.length,1);assert.ok(roomMetrics(r[0]).area<22);assert.notEqual(r[0].polygon[1].x,r[0].polygon[2].x);m.walls.forEach(w=>w.thickness=10);assert.deepEqual(deriveArchitecturalRooms(m),[]);});
test('columns and dangling observed walls surface review issues',()=>{const m=emptyArchitecture(0);m.walls=[{...wall('w',0,0,1,0),source:'observed'}];m.columns=[{id:'c',polygon:[{x:2,z:2},{x:3,z:2},{x:3,z:3},{x:2,z:3}],height:null,confidence:1}];const codes=architectureIssues(m,[{id:'camera',position:{x:2.5,z:2.5}}]).map(i=>i.code);for(const code of ['camera-in-column','dangling-wall','missing-wall-evidence'])assert.ok(codes.includes(code));});
