import test from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {ensureDeveloperTables,createDeveloper,listDevelopers,assignDeveloper,projectDeveloper,renameDeveloper,DeveloperError} from "../src/lib/imo3d/developer-management";
import {editProject,removeProject} from "../src/lib/imo3d/project-management";
function setup(){const db=new DatabaseSync(":memory:");db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE projects(id TEXT PRIMARY KEY,name TEXT,location TEXT,created_at TEXT);CREATE TABLE tours(id TEXT PRIMARY KEY,project_id TEXT,revision INTEGER,payload TEXT);INSERT INTO projects VALUES('a','Alpha','','today'),('b','Beta','','today');`);return db;}
test("developer migration preserves legacy projects and is repeatable",()=>{const db=setup();try{ensureDeveloperTables(db);ensureDeveloperTables(db);assert.equal(listDevelopers(db).length,0);assert.equal(projectDeveloper(db,"a"),undefined);assert.equal(db.prepare("SELECT count(*) n FROM projects").get()!.n,2);}finally{db.close();}});
test("multiple projects belong to a developer and can move without modifying tours",()=>{const db=setup();try{const first=createDeveloper(db,"First"),second=createDeveloper(db,"Second");assignDeveloper(db,"a",first.id);assignDeveloper(db,"b",first.id);assert.equal(projectDeveloper(db,"a"),projectDeveloper(db,"b"));editProject(db,"a",{name:"Alpha",location:"",developerId:second.id});assert.equal(projectDeveloper(db,"a"),second.id);assert.equal(projectDeveloper(db,"b"),first.id);assert.equal(renameDeveloper(db,first.id,"Renamed").name,"Renamed");editProject(db,"a",{name:"Alpha",location:"",developerId:null});assert.equal(projectDeveloper(db,"a"),undefined);}finally{db.close();}});
test("invalid assignment preserves project fields and deletion removes only its membership",()=>{const db=setup();try{const dev=createDeveloper(db,"First");assignDeveloper(db,"a",dev.id);assignDeveloper(db,"b",dev.id);assert.throws(()=>editProject(db,"a",{name:"Wrong",location:"",developerId:"missing"}),DeveloperError);assert.equal(db.prepare("SELECT name FROM projects WHERE id='a'").get()!.name,"Alpha");removeProject(db,"a","Alpha");assert.equal(projectDeveloper(db,"a"),undefined);assert.equal(projectDeveloper(db,"b"),dev.id);assert.equal(listDevelopers(db).length,1);}finally{db.close();}});
