import test from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import type {Tour} from "../src/lib/imo3d/model";
import {emptyArchitecture,deriveArchitecturalRooms} from "../src/lib/imo3d/architecture";
import {saveArchitecture,architectureSaveSchema,architectureReviewIssues} from "../src/lib/imo3d/architecture-storage";
import {removeTourScene} from "../src/lib/imo3d/scene-removal";
import {preserveAuthoredFloorState} from "../src/lib/imo3d/reconstruction-layout";
import {applySceneFloorAssignments} from "../src/lib/imo3d/floor-assignment";
import {hasReviewedArchitecture} from "../src/lib/imo3d/architecture-visibility";
import {mergeTourSpatial} from "../src/lib/imo3d/tour-merge";
function fixture(){
 const architecture=emptyArchitecture(0),corners=[{x:0,z:0},{x:4,z:0},{x:4,z:4},{x:0,z:4}];
 architecture.walls=corners.map((a,i)=>({id:`wall-${i}`,a,b:corners[(i+1)%4],thickness:.2,height:3,kind:"partition",confidence:1,source:"manual",evidenceIds:[]}));
 architecture.rooms=deriveArchitecturalRooms(architecture);architecture.rooms[0].cameraIds=["camera"];
 const tour:Tour={id:"tour",projectId:"project",title:"test",revision:1,published:false,createdAt:"2026-09-10",updatedAt:"2026-09-10",scenes:[{id:"camera",name:"Room",room:"Room",floor:0,position:{x:2,y:1.6,z:2},yaw:0,image:"/imo3d/a.jpg",preview:"/imo3d/a.jpg",thumbnail:"/imo3d/a.jpg",sourceName:"a.jpg",links:[]}],plans:[{floor:0,label:"Ground",kind:"estimated",reviewStatus:"rejected",bounds:{minX:0,minZ:0,maxX:4,maxZ:4},walls:[]}],quality:{positioned:1,components:1,depthScenes:0,warnings:[]},unit:{code:"",area:null,price:null,bedrooms:null,bathrooms:null}};
 const db=new DatabaseSync(":memory:");db.exec("CREATE TABLE tours(id TEXT PRIMARY KEY,project_id TEXT,revision INTEGER,published INTEGER,payload TEXT)");db.prepare("INSERT INTO tours VALUES(?,?,?,?,?)").run(tour.id,tour.projectId,tour.revision,0,JSON.stringify(tour));
 return{db,tour,architecture,input:architectureSaveSchema.parse({revision:1,floor:0,architecture})};
}
test("architectural draft is revision-safe and never silently approves rejected photo geometry",()=>{const f=fixture();try{const result=saveArchitecture(f.db,"tour",f.input);assert.equal(result.revision,2);assert.equal(result.plans[0].reviewStatus,"rejected");assert.equal(result.plans[0].architectureReview,"draft");assert.equal(hasReviewedArchitecture(result.plans[0]),false);assert.deepEqual(result.scenes,f.tour.scenes);assert.throws(()=>saveArchitecture(f.db,"tour",f.input),/تغيرت/);}finally{f.db.close();}});
test("explicit review accepts wall-derived inside-face rooms without altering metric calibration",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input);const next=saveArchitecture(f.db,"tour",{...f.input,revision:draft.revision,action:"review"});assert.equal(hasReviewedArchitecture(next.plans[0]),true);assert.equal(next.plans[0].architecture!.scale.status,"estimated");assert.equal(next.plans[0].architecture!.scale.metersPerUnit,null);assert.equal(next.plans[0].architecture!.rooms[0].polygon[0].x,.1);}finally{f.db.close();}});
test("review cannot approve arbitrary camera polygons, unsaved geometry, or camera crossing floors",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input);const invalid=structuredClone(f.architecture);invalid.rooms[0].polygon[0].x+=.3;assert.ok(architectureReviewIssues(invalid,f.tour).some(x=>x.includes("الوجوه الداخلية")));assert.throws(()=>saveArchitecture(f.db,"tour",{...f.input,architecture:invalid,action:"review",revision:draft.revision}),/احفظ/);const other=structuredClone(f.architecture);other.rooms[0].cameraIds=["other-tour-camera"];assert.throws(()=>saveArchitecture(f.db,"tour",{...f.input,architecture:other,revision:draft.revision}),/الدور نفسه/);}finally{f.db.close();}});
test("removing the last photo preserves architectural objects and prunes capture references",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input),next=removeTourScene(draft,"camera")!;assert.equal(next.plans.length,1);assert.equal(next.plans[0].architecture!.walls.length,4);assert.deepEqual(next.plans[0].architecture!.rooms[0].cameraIds,[]);assert.equal(next.published,false);}finally{f.db.close();}});
test("automatic reconstruction cannot replace an architectural coordinate frame",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input);const result=preserveAuthoredFloorState(draft.scenes,draft.plans,[{...draft.scenes[0],position:{x:100,y:1,z:100}}],f.tour.plans);assert.deepEqual(result.plans,draft.plans);assert.deepEqual(result.scenes,draft.scenes);}finally{f.db.close();}});
test("moving the last capture to a different floor preserves the original architectural drawing",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input);const result=applySceneFloorAssignments(draft,[{...draft.scenes[0],floor:1}]);assert.equal(result.plans.find(p=>p.floor===0)!.architecture!.walls.length,4);assert.equal(result.plans.find(p=>p.floor===0)!.architectureReview,"draft");assert.deepEqual(result.plans.find(p=>p.floor===0)!.architecture!.rooms[0].cameraIds,[]);}finally{f.db.close();}});

test("uploading after the final photo was removed retains the empty architectural floor",()=>{const f=fixture();try{const draft=saveArchitecture(f.db,"tour",f.input),empty=removeTourScene(draft,"camera")!;const result=mergeTourSpatial(empty,[{...f.tour.scenes[0],id:"new-camera",floor:1,position:null}]);assert.deepEqual(result.plans.find(p=>p.floor===0)!.architecture,empty.plans[0].architecture);}finally{f.db.close();}});
