"use client";
import {useEffect,useId,useRef,useState} from "react";
import type {Tour} from "@/lib/imo3d/model";
import {emptyArchitecture,deriveArchitecturalRooms,architectureIssues,type Architecture} from "@/lib/imo3d/architecture";
import {Dialog} from "./Dialog";
import {api} from "./client";
import {ArchitecturalPlanView} from "./ArchitecturalPlanView";
import "./architectural-editor.css";

type Point={x:number;z:number};
type Wall=Architecture["walls"][number];
const distance=(a:Point,b:Point)=>Math.hypot(b.x-a.x,b.z-a.z);
const numberValue=(value:string)=>value.trim()===""?null:Number(value);

export function ArchitecturalPlanEditor({tour,floor,onSaved,onClose}:{tour:Tour;floor:number;onSaved:(tour:Tour)=>void;onClose:()=>void}){
  const [draft,setDraft]=useState<Architecture>(()=>structuredClone(tour.plans.find(plan=>plan.floor===floor)?.architecture??emptyArchitecture(floor)));
  const [baseline]=useState(()=>JSON.stringify(draft));
  const [past,setPast]=useState<Architecture[]>([]),[future,setFuture]=useState<Architecture[]>([]);
  const [selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<"select"|"wall"|"column">("select"),[start,setStart]=useState<Point|null>(null);
  const [snap,setSnap]=useState(true),[guides,setGuides]=useState(false),[working,setWorking]=useState(false),[discard,setDiscard]=useState(false),[error,setError]=useState("");
  const [knownLength,setKnownLength]=useState(""),[openingKind,setOpeningKind]=useState<Architecture["openings"][number]["kind"]>("door");
  const [offset,setOffset]=useState(""),[width,setWidth]=useState(""),[hinge,setHinge]=useState<"start"|"end"|null>(null),[swing,setSwing]=useState<"left"|"right"|null>(null);
  const [splitPosition,setSplitPosition]=useState("50"),[notice,setNotice]=useState("");
  const [view,setView]=useState<"edit"|"2d"|"3d">("edit"),[previewScene,setPreviewScene]=useState("");
  const drag=useRef<{wallId:string;endpoint:"a"|"b";before:Architecture;pointerId:number}|null>(null);
  const svg=useRef<SVGSVGElement>(null),busy=useRef(false),gridId=useId();
  const scenes=tour.scenes.filter(scene=>scene.floor===floor),wall=draft.walls.find(item=>item.id===selected);
  const [frame,setFrame]=useState(()=>{const points=[...draft.walls.flatMap(item=>[item.a,item.b]),...scenes.flatMap(scene=>scene.position?[scene.position]:[])];const xs=points.map(p=>p.x),zs=points.map(p=>p.z),minX=Math.min(0,...xs),minZ=Math.min(0,...zs),maxX=Math.max(10,...xs),maxZ=Math.max(10,...zs);const size=Math.max(maxX-minX,maxZ-minZ)*1.35;return{x:(maxX+minX-size)/2,z:(maxZ+minZ-size)/2,size};});
  const unit=frame.size/800,step=.25,dirty=JSON.stringify(draft)!==baseline||start!==null;
  useEffect(()=>{if(!dirty)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",protect);return()=>window.removeEventListener("beforeunload",protect);},[dirty]);
  function close(){if(busy.current)return;if(drag.current){setDraft(drag.current.before);drag.current=null;}if(dirty)setDiscard(true);else onClose();}
  function edit(next:Architecture,topology=false){if(working)return;setPast(values=>[...values.slice(-49),draft]);setFuture([]);if(topology&&next.rooms.length){next={...next,rooms:[]};setNotice("تغيّرت الجدران؛ أعد استخراج الغرف المغلقة قبل تعديل أسمائها.");}setDraft(next);setError("");setDiscard(false);}
  function updateWall(patch:Partial<Wall>){if(wall)edit({...draft,walls:draft.walls.map(item=>item.id===wall.id?{...item,...patch,source:"manual"}:item)},true);}
  function dragPoint(event:React.PointerEvent<SVGSVGElement>,target:NonNullable<typeof drag.current>){const matrix=svg.current?.getScreenCTM();if(!matrix)return null;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());const point={x:p.x,z:p.y};if(!snap)return point;const nearby=target.before.walls.flatMap(item=>item.id===target.wallId?[item[target.endpoint==="a"?"b":"a"]]:[item.a,item.b]).find(candidate=>distance(candidate,point)<unit*12);return nearby??{x:Math.round(point.x/step)*step,z:Math.round(point.z/step)*step};}
  function beginDrag(event:React.PointerEvent<SVGCircleElement>,wallId:string,endpoint:"a"|"b"){if(mode!=="select"||event.button!==0||working)return;event.stopPropagation();drag.current={wallId,endpoint,before:structuredClone(draft),pointerId:event.pointerId};event.currentTarget.setPointerCapture(event.pointerId);}
  function finishDrag(cancel=false){const target=drag.current;if(!target)return;drag.current=null;if(cancel){setDraft(target.before);return;}if(JSON.stringify(draft.walls)===JSON.stringify(target.before.walls))return;setPast(values=>[...values.slice(-49),target.before]);setFuture([]);if(draft.rooms.length){setDraft(value=>({...value,rooms:[]}));setNotice("تغيّر موضع طرف الجدار؛ أعد استخراج الغرف المغلقة.");}setError("");setDiscard(false);}
  function pointer(event:React.PointerEvent<SVGSVGElement>){const matrix=svg.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());let point={x:p.x,z:p.y};if(snap){const nearby=draft.walls.flatMap(item=>[item.a,item.b]).find(candidate=>distance(candidate,point)<unit*12);point=nearby??{x:Math.round(point.x/step)*step,z:Math.round(point.z/step)*step};}if(!start){setStart(point);return;}if(distance(start,point)<.001)return;if(mode==="wall"){const id=crypto.randomUUID();edit({...draft,walls:[...draft.walls,{id,a:start,b:point,thickness:null,height:null,kind:"partition",confidence:1,source:"manual",evidenceIds:[]}]},true);setSelected(id);}else if(mode==="column"){if(Math.abs(point.x-start.x)<.001||Math.abs(point.z-start.z)<.001)return;edit({...draft,columns:[...draft.columns,{id:crypto.randomUUID(),polygon:[start,{x:point.x,z:start.z},point,{x:start.x,z:point.z}],height:null,confidence:1}]});}setStart(null);}
  function split(){if(!wall)return;const ratio=Number(splitPosition)/100,length=distance(wall.a,wall.b),cut=length*ratio;if(!Number.isFinite(ratio)||ratio<=0||ratio>=1){setError("حدد موضع التقسيم بين 0 و100 بالمئة.");return;}if(draft.openings.some(item=>item.wallId===wall.id&&item.offset<cut&&item.offset+item.width>cut)){setError("موضع التقسيم يقطع فتحة؛ اختر موضعًا خارج الأبواب والنوافذ.");return;}const id=crypto.randomUUID(),mid={x:wall.a.x+(wall.b.x-wall.a.x)*ratio,z:wall.a.z+(wall.b.z-wall.a.z)*ratio};edit({...draft,walls:draft.walls.flatMap(item=>item.id===wall.id?[{...item,b:mid},{...item,id,a:mid}]:[item]),openings:draft.openings.map(item=>item.wallId===wall.id&&item.offset>=cut?{...item,wallId:id,offset:item.offset-cut}:item)},true);}
  function addOpening(){if(!wall)return;const at=numberValue(offset),size=numberValue(width),length=distance(wall.a,wall.b);if(at===null||size===null||!Number.isFinite(at)||!Number.isFinite(size)||at<0||size<=0||at+size>length){setError("أدخل إزاحة وعرضًا صالحين ضمن طول الجدار، بوحدات الرسم.");return;}if(draft.openings.some(item=>item.wallId===wall.id&&at<item.offset+item.width&&at+size>item.offset)){setError("الفتحة تتداخل مع فتحة موجودة.");return;}edit({...draft,openings:[...draft.openings,{id:crypto.randomUUID(),wallId:wall.id,kind:openingKind,offset:at,width:size,height:null,sillHeight:null,hinge:openingKind==="door"?hinge:null,swing:openingKind==="door"?swing:null,confidence:1,source:"manual"}]});}
  async function save(){if(busy.current)return;const problems=architectureIssues(draft).filter(issue=>issue.severity==="error");if(problems.length){setError("يلزم تصحيح هندسة المخطط قبل الحفظ: "+problems.slice(0,4).map(issue=>issue.message).join(" · "));return;}busy.current=true;setWorking(true);setError("");try{const saved=await api<Tour>(`tours/${tour.id}/architecture`,{method:"PUT",body:JSON.stringify({revision:tour.revision,floor,architecture:draft})});onSaved(saved);onClose();}catch(reason){setError(reason instanceof Error?reason.message:"تعذر حفظ المخطط.");}finally{busy.current=false;setWorking(false);}}
  return <Dialog title={`محرر الجدران المعمارية — ${tour.title}`} wide className="imo-architecture-editor" onClose={close}>
    <p className="imo-muted">تحرير مركز الجدار وخصائصه. السماكة والارتفاع غير المعروفين يبقيان غير محددين. مواقع الصور دليل تقديري وليست حدودًا معمارية.</p>
    <fieldset disabled={working}>
      <div className="architecture-tools">{([["select","تحديد"],["wall","إضافة جدار"],["column","عمود مستطيل"]] as const).map(([value,label])=><button key={value} className={`imo-button ${mode===value?"primary":"secondary"}`} onClick={()=>{setMode(value);setStart(null);}}>{label}</button>)}
        {([["edit","تحرير"],["2d","معاينة 2D"],["3d","معاينة 3D"]] as const).map(([value,label])=><button key={value} className={`imo-button ${view===value?"primary":"secondary"}`} onClick={()=>{setView(value);setStart(null);}}>{label}</button>)}
        <button className="imo-button secondary" disabled={!past.length} onClick={()=>{setFuture(values=>[draft,...values]);setDraft(past.at(-1)!);setPast(values=>values.slice(0,-1));setStart(null);}}>تراجع</button>
        <button className="imo-button secondary" disabled={!future.length} onClick={()=>{setPast(values=>[...values,draft]);setDraft(future[0]);setFuture(values=>values.slice(1));setStart(null);}}>إعادة</button>
        <label><input type="checkbox" checked={snap} onChange={event=>setSnap(event.target.checked)}/>التقاط الزوايا والشبكة</label><label><input type="checkbox" checked={guides} onChange={event=>setGuides(event.target.checked)}/>مواقع الصور التقديرية</label>
        <button aria-label="تكبير الرسم" onClick={()=>setFrame(value=>({...value,x:value.x+value.size*.1,z:value.z+value.size*.1,size:value.size*.8}))}>+</button><button aria-label="تصغير الرسم" onClick={()=>setFrame(value=>({...value,x:value.x-value.size*.125,z:value.z-value.size*.125,size:value.size*1.25}))}>−</button>
      </div>
      <div className="architecture-workspace"><div className="architecture-board">
        {view!=="edit"?<ArchitecturalPlanView architecture={draft} scenes={scenes} current={previewScene} yaw={0} onSelect={id=>{setPreviewScene(id);setNotice("معاينة فقط: "+(scenes.find(scene=>scene.id===id)?.name??id));}} mode={view}/>:<svg ref={svg} viewBox={`${frame.x} ${frame.z} ${frame.size} ${frame.size}`} role="application" aria-label="تحرير مراكز الجدران" onPointerDown={event=>{if(event.button===0&&mode!=="select")pointer(event);}}
          onPointerMove={event=>{const target=drag.current;if(!target||target.pointerId!==event.pointerId||busy.current)return;const point=dragPoint(event,target);if(point)setDraft(previous=>({...previous,walls:previous.walls.map(item=>item.id===target.wallId?{...item,[target.endpoint]:point,source:"manual"}:item)}));}}
          onPointerUp={event=>{if(drag.current?.pointerId===event.pointerId)finishDrag();}}
          onPointerCancel={()=>finishDrag(true)} onLostPointerCapture={()=>finishDrag(true)}>
          <defs><pattern id={gridId} width={step} height={step} patternUnits="userSpaceOnUse"><path d={`M${step} 0H0V${step}`} fill="none" stroke="#dce3e8" strokeWidth={unit*.5}/></pattern></defs>
          <rect x={frame.x} y={frame.z} width={frame.size} height={frame.size} fill={`url(#${gridId})`}/>
          {draft.rooms.map(room=><g key={room.id}><polygon points={room.polygon.map(p=>`${p.x},${p.z}`).join(" ")} fill="#dcebe6" fillOpacity=".6"/><text x={room.polygon.reduce((sum,p)=>sum+p.x,0)/room.polygon.length} y={room.polygon.reduce((sum,p)=>sum+p.z,0)/room.polygon.length} textAnchor="middle" fontSize={unit*13}>{room.name}</text></g>)}
          {draft.columns.map(column=><polygon key={column.id} points={column.polygon.map(p=>`${p.x},${p.z}`).join(" ")} fill="#657582"/>)}
          {draft.walls.map(item=><g key={item.id} onPointerDown={event=>{if(mode==="select"){event.stopPropagation();setSelected(item.id);}}}>
            <line x1={item.a.x} y1={item.a.z} x2={item.b.x} y2={item.b.z} stroke="transparent" strokeWidth={Math.max(item.thickness??0,unit*18)}/>
            <line x1={item.a.x} y1={item.a.z} x2={item.b.x} y2={item.b.z} stroke={selected===item.id?"#007c77":"#293641"} strokeWidth={item.thickness??unit*1.8} strokeDasharray={item.thickness===null?`${unit*6} ${unit*3}`:undefined}/>
            {selected===item.id&&<><circle cx={item.a.x} cy={item.a.z} r={unit*7} fill="white" stroke="#007c77" strokeWidth={unit*2} style={{cursor:"grab"}} onPointerDown={event=>beginDrag(event,item.id,"a")}/><circle cx={item.b.x} cy={item.b.z} r={unit*7} fill="white" stroke="#007c77" strokeWidth={unit*2} style={{cursor:"grab"}} onPointerDown={event=>beginDrag(event,item.id,"b")}/></>}
          </g>)}
          {draft.openings.map(opening=>{const host=draft.walls.find(item=>item.id===opening.wallId);if(!host)return null;const length=distance(host.a,host.b),dx=(host.b.x-host.a.x)/length,dz=(host.b.z-host.a.z)/length;return <line key={opening.id} x1={host.a.x+dx*opening.offset} y1={host.a.z+dz*opening.offset} x2={host.a.x+dx*(opening.offset+opening.width)} y2={host.a.z+dz*(opening.offset+opening.width)} stroke={opening.kind==="window"?"#3ea2bd":"#fff"} strokeWidth={Math.max(host.thickness??0,unit*5)}/>;})}
          {guides&&scenes.flatMap(scene=>scene.position?[<circle key={scene.id} cx={scene.position.x} cy={scene.position.z} r={unit*4} fill="#aa7a25"><title>{scene.name} — موقع تقديري</title></circle>]:[])}
          {start&&<circle cx={start.x} cy={start.z} r={unit*6} fill="#007c77"/>}
        </svg>}<p>{view!=="edit"?"معاينة المسودة الحالية دون حفظ أو اعتماد. ارجع إلى تحرير لتعديل الهندسة.":mode==="select"?"اختر جدارًا واسحب طرفه الأبيض أو عدّل خصائصه رقميًا. الخط المتقطع يعني أن السماكة غير محددة.":start?"اضغط النقطة الثانية لإكمال العنصر.":"اضغط نقطتين لرسم العنصر. الشبكة: 0.25 وحدة رسم."}</p>
      </div><aside className="imo-form architecture-properties">
        <strong>خصائص الجدار</strong>
        {wall?<>
          <label>نوع الجدار<select value={wall.kind} onChange={event=>updateWall({kind:event.target.value as Wall["kind"]})}><option value="partition">قاطع داخلي</option><option value="exterior">خارجي</option><option value="structural">إنشائي</option></select></label>
          <div className="architecture-coordinate-fields">{(["a","b"] as const).flatMap(endpoint=>(["x","z"] as const).map(axis=><label key={endpoint+axis}>{endpoint.toUpperCase()} · {axis}<input type="number" step="any" value={wall[endpoint][axis]} onChange={event=>{const value=numberValue(event.target.value);if(value!==null&&Number.isFinite(value))updateWall({[endpoint]:{...wall[endpoint],[axis]:value}});}}/></label>))}</div>
          {(["thickness","height"] as const).map(key=><label key={key}>{key==="thickness"?"السماكة":"الارتفاع"} — وحدات الرسم<input type="number" step="any" min="0" placeholder="غير محدد" value={wall[key]??""} onChange={event=>{const value=numberValue(event.target.value);if(value===null||(Number.isFinite(value)&&value>0))updateWall({[key]:value});}}/></label>)}
          <small>الطول الحالي: {distance(wall.a,wall.b).toFixed(3)} وحدة رسم</small>
          <label>موضع تقسيم الجدار (%)<input type="number" min="1" max="99" value={splitPosition} onChange={event=>setSplitPosition(event.target.value)}/></label><button className="imo-button secondary" onClick={split}>تقسيم مع حفظ الفتحات</button>
          <button className="imo-button danger" onClick={()=>{edit({...draft,walls:draft.walls.filter(item=>item.id!==wall.id),openings:draft.openings.filter(item=>item.wallId!==wall.id)},true);setSelected(null);}}>حذف الجدار وفتحاته</button>
          <hr/><strong>فتحة في الجدار المحدد</strong><label>النوع<select value={openingKind} onChange={event=>setOpeningKind(event.target.value as typeof openingKind)}><option value="door">باب</option><option value="window">نافذة</option><option value="opening">فتحة حرة</option></select></label>
          <label>الإزاحة من A (وحدة رسم)<input type="number" min="0" step="any" value={offset} onChange={event=>setOffset(event.target.value)}/></label><label>العرض (وحدة رسم)<input type="number" min="0" step="any" value={width} onChange={event=>setWidth(event.target.value)}/></label>
          {openingKind==="door"&&<><label>المفصلة<select value={hinge??""} onChange={event=>setHinge(event.target.value===""?null:event.target.value as "start"|"end")}><option value="">غير محددة</option><option value="start">بداية الفتحة</option><option value="end">نهاية الفتحة</option></select></label><label>جهة الفتح نسبةً لاتجاه A إلى B<select value={swing??""} onChange={event=>setSwing(event.target.value===""?null:event.target.value as "left"|"right")}><option value="">غير محددة</option><option value="left">يسار</option><option value="right">يمين</option></select></label></>}
          <button className="imo-button secondary" onClick={addOpening}>إضافة الفتحة</button>
          {draft.openings.filter(item=>item.wallId===wall.id).map((item,index)=><div key={item.id} className="architecture-opening-details"><div className="architecture-opening-row"><span>{item.kind==="door"?"باب":item.kind==="window"?"نافذة":"فتحة"} {index+1} · {item.width}</span><button aria-label={`حذف الفتحة ${index+1}`} onClick={()=>edit({...draft,openings:draft.openings.filter(opening=>opening.id!==item.id)})}>حذف</button></div>{(["offset","width","height","sillHeight"] as const).map(key=><label key={key}>{{offset:"الإزاحة",width:"العرض",height:"الارتفاع",sillHeight:"ارتفاع الجلسة"}[key]} (وحدة رسم)<input type="number" step="any" min="0" placeholder="غير محدد" value={item[key]??""} onChange={event=>{const value=numberValue(event.target.value);if(value===null&&(key==="offset"||key==="width"))return;if(value!==null&&(!Number.isFinite(value)||value<0||((key==="width"||key==="height")&&value===0)))return;edit({...draft,openings:draft.openings.map(opening=>opening.id===item.id?{...opening,[key]:value,source:"manual"}:opening)});}}/></label>)}</div>)}
          <hr/><strong>المقياس والأبعاد</strong><label>طول الجدار المعروف بالمتر<input type="number" min="0" step="any" value={knownLength} onChange={event=>setKnownLength(event.target.value)}/></label>
          <button className="imo-button secondary" onClick={()=>{const value=Number(knownLength),length=distance(wall.a,wall.b);if(!Number.isFinite(value)||value<=0||length<=0){setError("أدخل طولًا معروفًا موجبًا بالمتر.");return;}edit({...draft,scale:{...draft.scale,status:"calibrated",metersPerUnit:value/length}});setNotice("تمت معايرة المقياس العام فقط؛ لم تتحرك الجدران أو مواقع الصور.");}}>معايرة المقياس العام</button>
          <button className="imo-button secondary" disabled={draft.scale.status!=="calibrated"} onClick={()=>{const value=Number(knownLength),factor=draft.scale.metersPerUnit,length=distance(wall.a,wall.b);if(!factor||!Number.isFinite(value)||value<=0||length<=0){setError("يلزم مقياس معاير وطول موجب.");return;}if(!window.confirm("سيُحرّك هذا الإجراء نهاية B لهذا الجدار وحده، وقد يفصل الجدران المتصلة. ستُمسح الغرف المشتقة لإعادة استخراجها. متابعة؟"))return;const ratio=value/factor/length;updateWall({b:{x:wall.a.x+(wall.b.x-wall.a.x)*ratio,z:wall.a.z+(wall.b.z-wall.a.z)*ratio}});}}>تصحيح طول هذا الجدار بتحريك B</button>
        </>:<p className="imo-muted">أضف جدارًا أو حدده من الرسم. يمكن إدخال الإحداثيات رقميًا.</p>}
        <label>وحدة الأبعاد<select value={draft.scale.displayUnit} onChange={event=>edit({...draft,scale:{...draft.scale,displayUnit:event.target.value as "mm"|"cm"|"m"}})}><option value="mm">مم</option><option value="cm">سم</option><option value="m">م</option></select></label>
        <strong>الغرف المغلقة</strong><button className="imo-button secondary" onClick={()=>{try{const rooms=deriveArchitecturalRooms(draft);edit({...draft,rooms});setNotice(rooms.length?`تم استخراج ${rooms.length} غرفة مغلقة. راجع الأسماء.`:"لا توجد حلقات جدران مغلقة قابلة للاستخراج؛ راجع اتصال الأطراف.");}catch(reason){setError(reason instanceof Error?reason.message:"تعذر استخراج الغرف.");}}}>استخراج الغرف من الجدران</button>
        {draft.rooms.map(room=><label key={room.id}>اسم الغرفة<input value={room.name} maxLength={100} onChange={event=>edit({...draft,rooms:draft.rooms.map(item=>item.id===room.id?{...item,name:event.target.value}:item)})}/></label>)}
        {!!draft.columns.length&&<><strong>الأعمدة</strong>{draft.columns.map((column,index)=><div key={column.id}><label>ارتفاع العمود {index+1} (وحدة رسم)<input type="number" step="any" min="0" placeholder="غير محدد" value={column.height??""} onChange={event=>{const value=numberValue(event.target.value);if(value===null||(Number.isFinite(value)&&value>0))edit({...draft,columns:draft.columns.map(item=>item.id===column.id?{...item,height:value}:item)});}}/></label><button className="imo-button secondary" onClick={()=>edit({...draft,columns:draft.columns.filter(item=>item.id!==column.id)})}>حذف العمود {index+1}</button></div>)}</>}
      </aside></div>
    </fieldset>
    <p className="imo-muted">{draft.scale.status==="calibrated"?`المقياس معاير: ${draft.scale.metersPerUnit?.toFixed(5)} متر / وحدة.`:"المقياس تقديري؛ لا توجد أبعاد مترية مؤكدة."} هذه أدوات مراجعة يدوية؛ لا تُثبت صحة إعادة البناء من الصور.</p>
    {notice&&<p role="status">{notice}</p>}{error&&<p className="imo-error" role="alert">{error}</p>}
    {discard&&<div role="alert"><p>لديك تعديلات غير محفوظة.</p><button className="imo-button secondary" onClick={()=>setDiscard(false)}>متابعة التحرير</button><button className="imo-button danger" onClick={onClose}>تجاهل وإغلاق</button></div>}
    <div className="imo-dialog-actions"><button className="imo-button primary" disabled={working||start!==null} onClick={save}>{working?"جارٍ الحفظ…":"حفظ المسودة المعمارية"}</button><button className="imo-button secondary" disabled={working} onClick={close}>إغلاق</button></div>
  </Dialog>;
}



