'use client';
import {useEffect,useState} from 'react';
import {withBasePath} from '@/lib/imo3d/base-path';
type Connection={id:string;project_id:string;projectName:string;created_at:string;revoked_at:string|null};
export function ChatGPTSettings(){
 const [connections,setConnections]=useState<Connection[]>([]),[error,setError]=useState(''),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false);
 // The connector lives on this app's own host (the OAuth issuer), not on the suite's domain.
 const [endpoint,setEndpoint]=useState('');
 useEffect(()=>{let active=true;void fetch(withBasePath('/.well-known/oauth-protected-resource')).then(response=>response.ok?response.json():null).then(value=>{if(active&&typeof value?.resource==='string')setEndpoint(value.resource);}).catch(()=>{});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;void fetch(withBasePath('/api/imo3d-chatgpt/connections')).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(active)setConnections(data);}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;};},[]);
 return <section className="imo-form" style={{borderTop:'1px solid #dce6e0',paddingTop:20,marginTop:24}}><h3>الربط مع حسابك في ChatGPT</h3><p>التحليل يبدأ من محادثتك في ChatGPT باستخدام اشتراكك، ولا يحتاج مفتاح OpenAI API. اختر إضافة اتصال خاص في ChatGPT، ثم أدخل رابط MCP واختر OAuth.</p><label>رابط الربط<input dir="ltr" readOnly value={endpoint} onFocus={event=>event.target.select()}/></label><div className="imo-dialog-actions"><button type="button" className="imo-button secondary" onClick={()=>{void navigator.clipboard.writeText(endpoint).then(()=>setCopied(true)).catch(()=>setError('حدد الرابط وانسخه يدويًا.'));}}>{copied?'تم نسخ الرابط':'نسخ الرابط'}</button><a className="imo-button secondary" href="https://chatgpt.com/plugins" target="_blank" rel="noreferrer">فتح ChatGPT</a></div><p>بعد الربط اكتب: «حلل جميع صور الجولة، تحقق من الأبواب والغرف، واحفظ مخطط 2D كمسودة مع توضيح الأجزاء غير المؤكدة». توافر الربط وحدود التحليل يعتمدان على حساب ChatGPT.</p>
 <h4>الاتصالات المسموح لها</h4>{!connections.some(item=>!item.revoked_at)&&<p>لا يوجد اتصال فعّال بعد.</p>}{connections.filter(item=>!item.revoked_at).map(item=><div key={item.id}><span>ChatGPT · {item.projectName} · {new Date(item.created_at).toLocaleDateString('ar')}</span><button type="button" className="imo-button secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch(withBasePath('/api/imo3d-chatgpt/connections'),{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id})});if(!response.ok)throw Error('تعذر إلغاء الربط.');setConnections(previous=>previous.filter(value=>value.id!==item.id));}catch(error){setError(error instanceof Error?error.message:'تعذر إلغاء الربط');}finally{setBusy(false);}}}>إلغاء هذا الربط</button></div>)}{error&&<p role="alert" className="imo-error">{error}</p>}</section>;
}
