"use client";
import {useEffect,useMemo,useState} from 'react';
import type {Tour} from '@/lib/imo3d/model';
import type {PhotoEdit} from '@/lib/imo3d/photo-edits';
import {PanoramaPlacement} from './PanoramaPlacement';
import {api} from './client';
export function PhotoEditPanel({tour,disabled,onSaved}:{tour:Tour;disabled:boolean;onSaved:(tour:Tour)=>void}){
 const [sceneId,setSceneId]=useState(tour.scenes[0]?.id??''),[pose,setPose]=useState({yaw:0,pitch:0,fov:50}),[prompt,setPrompt]=useState('أزل الكاميرا أو الحامل الظاهر في المكان المحدد وأكمل الخلفية بشكل طبيعي مع إبقاء بقية الصورة كما هي.');
 const [jobs,setJobs]=useState<PhotoEdit[]>(tour.photoEdits??[]),[online,setOnline]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState<'original'|'draft'>('draft');
 useEffect(()=>{let active=true;const poll=async()=>{try{const result=await api<{jobs:PhotoEdit[];workerOnline:boolean}>(`tours/${tour.id}/photo-edits`);if(active){setJobs(old=>JSON.stringify(old)===JSON.stringify(result.jobs)?old:result.jobs);setOnline(result.workerOnline);}}catch(e){if(active)setError(e instanceof Error?e.message:'تعذر قراءة حالة التحرير.');}};void poll();const timer=setInterval(()=>void poll(),6000);return()=>{active=false;clearInterval(timer);};},[tour.id,tour.revision]);
 const scene=tour.scenes.find(s=>s.id===sceneId)??tour.scenes[0],job=[...jobs].reverse().find(j=>j.sceneId===scene?.id&&j.status!=='cancelled'),locked=disabled||busy;
 const act=async(action:string,jobId?:string)=>{if(!scene)return;setBusy(true);setError('');try{const latest=await api<Tour>(`tours/${tour.id}`);const saved=await api<Tour>(`tours/${tour.id}/photo-edits`,{method:'POST',body:JSON.stringify({revision:latest.revision,action,sceneId:scene.id,...(action==='create'?{...pose,prompt}:{}),...(jobId?{jobId}:{})})});onSaved(saved);setJobs(saved.photoEdits??[]);}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ التعديل.');}finally{setBusy(false);}};
 const preview=useMemo(()=>!scene?null:job?.status==='draft'&&job.result&&view==='draft'?{...scene,...job.result,presentation:undefined,detail:undefined}:view==='original'?{...scene,presentation:undefined}:scene,[scene,job,view]);
 if(!scene||!preview)return <p>أضف الصور أولًا.</p>;
 const processing=job&&['queued','running'].includes(job.status);
 return <section><h3>تحرير الصورة بالذكاء الاصطناعي</h3><p className="imo-muted">حدّد العنصر المراد إزالته واكتب المطلوب. يُعدّل الجزء المحدد فقط، وتبقى الصورة الأصلية محفوظة. راجع المسودة قبل اعتمادها في الجولة.</p>
 <label className="imo-form">الصورة<select disabled={locked} value={scene.id} onChange={e=>{setSceneId(e.target.value);setPose({yaw:0,pitch:0,fov:50});}}>{tour.scenes.map((s,i)=><option key={s.id} value={s.id}>{i+1} — {s.name}</option>)}</select></label>
 <PanoramaPlacement key={`${scene.id}/${job?.status}/${view}/${scene.presentation?.image}`} scene={preview} regionSize={pose.fov} focusRegion yaw={pose.yaw} pitch={pose.pitch} disabled={locked||!!processing} onPick={(yaw,pitch)=>setPose({...pose,yaw,pitch})}/>
 <div className="imo-dialog-actions"><button type="button" className="imo-button secondary" disabled={locked||!!processing} onClick={()=>setPose({yaw:0,pitch:-90,fov:85})}>تحديد الحامل أسفل الكاميرا</button>{job?.result&&<button type="button" className="imo-button secondary" onClick={()=>setPose({yaw:job.yaw,pitch:job.pitch,fov:job.fov})}>عرض مكان التعديل</button>}{job?.result&&<button type="button" className="imo-button secondary" onClick={()=>setView(view==='draft'?'original':'draft')}>{view==='draft'?'مقارنة مع الأصل':'عرض المسودة'}</button>}</div>
 <div className="imo-form"><label>حجم المنطقة المحددة <input disabled={locked||!!processing} type="range" min={10} max={100} value={pose.fov} onChange={e=>setPose({...pose,fov:Number(e.target.value)})}/></label><small>{pose.pitch===-90?'المنطقة المحددة: أسفل الكاميرا':'اضغط على العنصر داخل الصورة لتحديد مركز التعديل.'}</small><label>ما الذي تريد تغييره؟<textarea disabled={locked||!!processing} maxLength={1200} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label></div>
 <p role="status">{processing?(job.status==='queued'?'الطلب في الانتظار؛ ستستمر المعالجة حتى بعد إغلاق هذه الصفحة.':'جارٍ تحرير الجزء المحدد ومراجعة النتيجة…'):job?.status==='draft'?'المسودة جاهزة للمراجعة والاعتماد.':online?'عامل ChatGPT على جهاز المعالجة متصل.':'عامل ChatGPT غير متصل حاليًا؛ سيبقى الطلب في الانتظار حتى يتصل الجهاز.'}</p>
 {job?.status==='draft'&&job.review&&<details><summary>ملاحظات مراجعة التعديل</summary><p>{job.review}</p></details>}
 {job?.error&&<p role="alert" className="imo-error">{job.error}</p>}{error&&<p role="alert" className="imo-error">{error}</p>}
 <div className="imo-dialog-actions"><button className="imo-button primary" disabled={locked||!!processing||prompt.trim().length<5} onClick={()=>void act('create')}>إنشاء مسودة التعديل</button>{processing&&<button className="imo-button secondary" disabled={locked} onClick={()=>void act('cancel',job.id)}>إلغاء الطلب</button>}{job?.status==='draft'&&<><button className="imo-button primary" disabled={locked} onClick={()=>void act('apply',job.id)}>اعتماد المسودة في الجولة</button><button className="imo-button secondary" disabled={locked} onClick={()=>void act('cancel',job.id)}>رفض المسودة</button></>}{scene.presentation&&<button className="imo-button secondary" disabled={locked} onClick={()=>void act('restore')}>استعادة الصورة الأصلية</button>}</div>
 </section>;
}
