"use client";
/* eslint-disable @next/next/no-img-element */
import {useEffect,useRef,useState} from "react";
import {AdminSettings} from './AdminSettings';
import {AIPlanPanel} from "./AIPlanPanel";
import {DeveloperDirectory} from "./DeveloperDirectory";
import type {Developer,Lead,Project,Scene,Tour} from "@/lib/imo3d/model";
import {api,number} from "./client";
import {uploadPanorama} from "./panorama-upload";
import {Icon} from "./Icon";
import {Dialog} from "./Dialog";
import {InteractiveFloorPlan} from "./InteractiveFloorPlan";
import {MeasurementDialog} from "./MeasurementDialog";
import {BrandingEditor} from "./BrandingEditor";
import {IntegrationKeys} from "./IntegrationKeys";
import {ProjectManagementDialog,TourDeletionDialog} from "./ManagementDialogs";
import {TourPreviewDialog} from "./TourPreviewDialog";
import {ManualLinkEditor} from "./ManualLinkEditor";
import {FloorSelector} from "./FloorSelector";
import {ArchitecturalPlanEditor} from "./ArchitecturalPlanEditor";
import {ArchitectureReviewControls} from "./ArchitectureReviewControls";
import {SemanticRoomsEditor} from "./SemanticRoomsEditor";
import {ProjectUsageDialog} from "./ProjectUsageDialog";
import {LeadInbox} from "./LeadInbox";
import {unnamedRoom} from "./room-labels";
import {processingActive,type ProcessingJob} from "@/lib/imo3d/processing-model";
import "./studio-workflows.css";
import "./liquid-glass.css";

type Dashboard={features?:{cloud?:boolean;privateExample:{id:string;title:string;thumbnail:string}|null};developers:Developer[];projects:Project[];tours:Tour[];leads:Lead[];leadTotal?:number};
export default function Studio(){
  const [data,setData]=useState<Dashboard|null>(null),[auth,setAuth]=useState(false),[error,setError]=useState("");
  const [view,setView]=useState<"projects"|"leads">("projects"),[query,setQuery]=useState(""),[projectId,setProjectId]=useState("");
  const [modal,setModal]=useState<"project"|"tour"|null>(null),[selected,setSelected]=useState<Tour|null>(null),[working,setWorking]=useState(false);
  const [developerId,setDeveloperId]=useState<string|null>(null);
  const [notice,setNotice]=useState(""); const [adminSettings,setAdminSettings]=useState(false);
  const [usageProject,setUsageProject]=useState<string|null>(null);
  const [managedProject,setManagedProject]=useState<Project|null>(null),[tourRemoval,setTourRemoval]=useState<Tour|null>(null);
  const [preview,setPreview]=useState<{projectId:string;tourId?:string;sceneId?:string}|null>(null);
  const [editorBlocked,setEditorBlocked]=useState(false),[settings,setSettings]=useState<{kind:"branding"|"api";projectId:string}|null>(null);
  const refresh=async()=>{const next=await api<Dashboard>("dashboard");setData(next);setAuth(false);};
  useEffect(()=>{let alive=true;api<{admin:boolean}>("session").then(session=>{if(!alive)return;if(!session.admin){setAuth(true);return;}return api<Dashboard>("dashboard").then(result=>{if(alive)setData(result);});}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
  const run=async(action:()=>Promise<void>)=>{setWorking(true);setError("");try{await action();}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية");}finally{setWorking(false);}};
  const openTour=(tour:Tour)=>void run(async()=>setSelected(await api<Tour>(`tours/${tour.id}`)));
  const requestTourRemoval=(tour:Tour)=>void run(async()=>setTourRemoval(await api<Tour>(`tours/${tour.id}`)));
  const changeView=(next:"projects"|"leads")=>{if(editorBlocked){setError("احفظ تعديلات الجولة وانتظر اكتمال الرفع قبل مغادرة المحرر.");return;}setView(next);if(next==="projects"){setDeveloperId(null);setProjectId("");}setSelected(null);void refresh().catch(e=>setError(e.message));};
  if(auth)return <main className="imo-shell imo-login"><div className="imo-login-card"><Brand/><h1>دخول الاستوديو</h1><p>إدارة مشاريعك وجولاتك من مكان واحد.</p><form className="imo-form" onSubmit={e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));void run(async()=>{await api("session",{method:"POST",body:JSON.stringify({password})});await refresh();});}}><label>رمز الإدارة<input type="password" name="password" autoComplete="current-password" required/></label>{error&&<p className="imo-error" role="alert">{error}</p>}<button className="imo-button primary" disabled={working}>دخول</button></form></div></main>;
  if(!data)return <main className="imo-shell imo-load">{error?<><p role="alert">{error}</p><button className="imo-button primary" onClick={()=>window.location.reload()}>إعادة المحاولة</button></>:<><span className="imo-spinner"/><p>جارٍ فتح الاستوديو…</p></>}</main>;
  const scopedProjects=data.projects.filter(project=>developerId===null||(project.developerId??"")===developerId);
  const visibleTours=data.tours.filter(t=>scopedProjects.some(project=>project.id===t.projectId)).filter(t=>(!projectId||t.projectId===projectId)&&`${t.title} ${data.projects.find(p=>p.id===t.projectId)?.name}`.includes(query));
  const scopedTours=data.tours.filter(tour=>scopedProjects.some(project=>project.id===tour.projectId));
  const activeProject=scopedProjects.find(project=>project.id===projectId)||scopedProjects[0];
  return <main className="imo-shell imo-studio"><aside className="imo-sidebar"><a href="/imo3d" onClick={event=>{if(editorBlocked){event.preventDefault();setError("احفظ تعديلات الجولة قبل العودة إلى الاستوديو.");}}}><Brand/></a><div className="imo-sidebar-label">مساحة العمل</div><nav><button aria-label="المطورون" className={view==="projects"?"active":""} onClick={()=>changeView("projects")}><Icon name="grid"/>المطورون<span>{data.developers?.length??0}</span></button><button aria-label="طلبات الاهتمام" className={view==="leads"?"active":""} onClick={()=>changeView("leads")}><Icon name="people"/>طلبات الاهتمام<span>{(data.leadTotal??data.leads.length)}</span></button>{data.features?.cloud&&<button aria-label="الإعدادات" onClick={()=>setAdminSettings(true)}><Icon name="settings"/>الإعدادات</button>}</nav><div className="imo-sidebar-bottom"><div className="imo-brand-avatar">B</div><div><strong>BMK Solutions</strong><small>IMO 3D Studio</small></div></div></aside>
    <div className="imo-workspace"><header className="imo-studio-top"><div><span className="imo-breadcrumb">الاستوديو</span><span>/</span><b>{selected?selected.title:view==="leads"?"طلبات الاهتمام":"المطورون"}</b></div><span className="imo-private"><span className="imo-status-dot"/> مساحة الإدارة</span></header>
      {error&&<div className="imo-banner error" role="alert">{error}<button aria-label="إغلاق الرسالة" onClick={()=>setError("")}><Icon name="close"/></button></div>}
      {notice&&<div className="imo-banner" role="status">{notice}<button aria-label="إغلاق الرسالة" onClick={()=>setNotice("")}><Icon name="close"/></button></div>}
      {selected?<Editor key={selected.id} initial={selected} onBlockedChange={setEditorBlocked} onDelete={requestTourRemoval} onPreview={(tour,sceneId)=>setPreview({projectId:tour.projectId,tourId:tour.id,sceneId})} onSettings={kind=>{if(kind==="project")setManagedProject(data.projects.find(project=>project.id===selected.projectId)||null);else setSettings({kind,projectId:selected.projectId});}} onBack={()=>{setSelected(null);void refresh().catch(e=>setError(e.message));}} onChange={tour=>{setSelected(tour);setData(previous=>previous?{...previous,tours:previous.tours.map(t=>t.id===tour.id?tour:t)}:previous);}} onError={setError} onNotice={setNotice}/>:view==="leads"?<LeadInbox projects={data.projects}/>:<div className="imo-page">
        <DeveloperDirectory developers={data.developers??[]} projects={data.projects} selected={developerId} onSelect={id=>{setDeveloperId(id);setProjectId("");}} onRefresh={refresh}/>{developerId!==null&&<>
        <div className="imo-page-heading"><div><span className="imo-eyebrow">من الصورة إلى المكان</span><h1>مشاريعك، في بُعد آخر<span>.</span></h1><p>أضف لقطاتك، جهّز الجولة، واجعل المكان أقرب.</p></div><button className="imo-button primary" onClick={()=>setModal("project")}><Icon name="plus"/>مشروع جديد</button></div>
        <div className="imo-metrics"><div><span>المشاريع</span><strong>{number(scopedProjects.length)}</strong><Icon name="folder"/></div><div><span>الجولات</span><strong>{number(scopedTours.length)}</strong><Icon name="eye"/></div><div><span>لقطات 360°</span><strong>{number(scopedTours.reduce((n,t)=>n+t.scenes.length,0))}</strong><Icon name="layers"/></div><div><span>الجولات المنشورة</span><strong>{number(scopedTours.filter(tour=>tour.published).length)}</strong><Icon name="eye"/></div></div>
        {scopedProjects.length>0&&<div className="imo-tour-grid" aria-label="مشاريع المطوّر">{scopedProjects.map(project=><button key={project.id} className={`imo-button ${projectId===project.id?"primary":"secondary"}`} style={{minHeight:80,whiteSpace:"normal"}} onClick={()=>setProjectId(project.id)}><Icon name="folder"/><strong>{project.name}</strong><span>{number(scopedTours.filter(tour=>tour.projectId===project.id).length)} جولات</span></button>)}</div>}
        <div className="imo-section-heading"><div className="imo-filter"><select aria-label="تصفية حسب المشروع" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">كل المشاريع</option>{scopedProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><label className="imo-search"><Icon name="search" size={18}/><input aria-label="البحث في الجولات" placeholder="ابحث عن جولة…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><button className="imo-button secondary" disabled={!scopedProjects.length} onClick={()=>setModal("tour")}><Icon name="plus" size={18}/>إضافة جولة</button></div>
        {activeProject&&<div className="imo-project-settings-row"><span>إعدادات {activeProject.name}{activeProject.location&&<small>{activeProject.location}</small>}</span><button className="imo-button secondary" disabled={working} onClick={()=>setManagedProject(activeProject)}><Icon name="settings" size={17}/>إدارة المشروع</button><button className="imo-button secondary" disabled={working} onClick={()=>setPreview({projectId:activeProject.id})}><Icon name="eye" size={17}/>معاينة المشروع</button><button className="imo-button secondary" onClick={()=>setSettings({kind:"branding",projectId:activeProject.id})}><Icon name="eye" size={17}/>الاسم والشعار</button><button className="imo-button secondary" onClick={()=>setUsageProject(activeProject.id)}><Icon name="layers" size={17}/>الاستهلاك والتكلفة</button><button className="imo-button secondary" onClick={()=>setSettings({kind:"api",projectId:activeProject.id})}><Icon name="link" size={17}/>تكامل API</button></div>}
        {visibleTours.length?<div className="imo-tour-grid">{visibleTours.map(tour=><article className="imo-tour-card" key={tour.id}><button className="imo-tour-cover" onClick={()=>openTour(tour)}>{tour.scenes[0]?<img src={tour.scenes[0].preview} alt={tour.title}/>:<div className="imo-cover-empty"><Icon name="upload" size={36}/><span>أضف لقطات الجولة</span></div>}<span className={`imo-tour-badge ${tour.published?"live":""}`}>{tour.published?"رابط متاح":"مسودة"}</span>{tour.scenes.length>0&&<span className="imo-cover-count">360° <i/> {number(tour.scenes.length)} لقطة</span>}</button><div className="imo-tour-card-body"><div className="imo-card-project"><small>{data.projects.find(p=>p.id===tour.projectId)?.name}</small><button className="imo-delete-tour-card" disabled={working} aria-label={`حذف الجولة ${tour.title}`} title="حذف الجولة" onClick={()=>requestTourRemoval(tour)}><Icon name="trash" size={17}/></button></div><h3>{tour.title}</h3><div><span>{tour.scenes.every(s=>unnamedRoom(s.room))?"الغرف تحتاج تسمية":number(new Set(tour.scenes.filter(s=>!unnamedRoom(s.room)).map(s=>s.room)).size)+" غرف مسمّاة"} <i/> {number(tour.plans.length)} أدوار</span><button className="imo-icon" aria-label={`إدارة ${tour.title}`} onClick={()=>openTour(tour)}><Icon name="arrow"/></button></div><button className="imo-card-preview" disabled={working||!tour.scenes.length} onClick={()=>setPreview({projectId:tour.projectId,tourId:tour.id})}><Icon name="eye" size={16}/>معاينة قبل النشر</button></div></article>)}</div>:<div className="imo-empty"><Icon name="folder" size={38}/><h3>{query?"لا توجد نتائج":"مكانك الأول يبدأ هنا"}</h3><p>{query?"جرّب اسمًا آخر للجولة أو المشروع.":"أنشئ مشروعًا، ثم أضف جولة وارفع صور 360 دفعة واحدة."}</p></div>}
        {data.features?.privateExample&&!data.tours.some(t=>t.id===data.features?.privateExample?.id)&&<div className="imo-reference"><img src={data.features.privateExample.thumbnail} alt="معاينة الجولة المحلية"/><div><h3>{data.features.privateExample.title}</h3><p>استورد نسخة معاينة من الجولة المحفوظة على جهازك.</p></div><button disabled={working} className="imo-button secondary" onClick={()=>void run(async()=>{const example=await api<Tour>("example",{method:"POST"});await refresh();setSelected(example);})}>فتح الجولة المحلية <Icon name="arrow" size={18}/></button></div>}
      </>}
      </div>}
    </div>
    {adminSettings&&<AdminSettings onClose={()=>setAdminSettings(false)} onSaved={()=>{setAdminSettings(false);setNotice("تم تغيير كلمة المرور. استخدم الكلمة الجديدة عند الدخول من الأجهزة الأخرى.");}}/>}
    {modal&&<Dialog title={modal==="project"?"مشروع جديد":"جولة جديدة"} onClose={()=>setModal(null)}><form className="imo-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void run(async()=>{if(modal==="project"){const project=await api<Project>("projects",{method:"POST",body:JSON.stringify({name:form.get("name"),location:form.get("location"),developerId:form.get("developerId")||null})});await refresh();setDeveloperId(project.developerId??"");setProjectId(project.id);setModal("tour");}else{const tour=await api<Tour>("tours",{method:"POST",body:JSON.stringify({projectId:form.get("projectId"),title:form.get("name")})});await refresh();setSelected(tour);setModal(null);}});}}>
      {modal==="tour"&&<label>المشروع<select name="projectId" defaultValue={projectId||scopedProjects[0]?.id}>{scopedProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>}
      <label>{modal==="project"?"اسم المشروع":"اسم الجولة أو الوحدة"}<input name="name" required minLength={2} maxLength={120} placeholder={modal==="project"?"مثال: مساكن الروضة":"مثال: شقة ١٠١"}/></label>
      {modal==="project"&&<label>المطوّر<select name="developerId" defaultValue={developerId??""}><option value="">بدون مطوّر</option>{(data.developers??[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
      {modal==="project"&&<label>المدينة أو الموقع<input name="location" maxLength={160}/></label>}<button className="imo-button primary" disabled={working}>{working?"جارٍ الإنشاء…":"إنشاء"}</button>
    </form></Dialog>}
    {managedProject&&<ProjectManagementDialog key={managedProject.id} project={managedProject} developers={data.developers??[]} tours={data.tours.filter(tour=>tour.projectId===managedProject.id)} onClose={()=>setManagedProject(null)} onSaved={project=>{setData(previous=>previous?{...previous,projects:previous.projects.map(item=>item.id===project.id?project:item)}:previous);setManagedProject(null);setNotice("تم حفظ بيانات المشروع.");}} onDeleted={warning=>{const id=managedProject.id;setData(previous=>{if(!previous)return previous;const removed=new Set(previous.tours.filter(tour=>tour.projectId===id).map(tour=>tour.id));return {...previous,projects:previous.projects.filter(project=>project.id!==id),tours:previous.tours.filter(tour=>tour.projectId!==id),leads:previous.leads.filter(lead=>!removed.has(lead.tourId))};});setSelected(previous=>previous?.projectId===id?null:previous);setProjectId(previous=>previous===id?"":previous);setManagedProject(null);setEditorBlocked(false);setNotice(warning||"تم حذف المشروع ومحتوياته.");void refresh().catch(reason=>setError(reason.message));}}/>}
    {tourRemoval&&<TourDeletionDialog key={tourRemoval.id} tour={tourRemoval} onClose={()=>setTourRemoval(null)} onDeleted={warning=>{const id=tourRemoval.id;setData(previous=>previous?{...previous,tours:previous.tours.filter(tour=>tour.id!==id),leads:previous.leads.filter(lead=>lead.tourId!==id)}:previous);setSelected(previous=>previous?.id===id?null:previous);setTourRemoval(null);setEditorBlocked(false);setNotice(warning||"تم حذف الجولة وصورها.");void refresh().catch(reason=>setError(reason.message));}}/>}
    {preview&&<TourPreviewDialog tours={data.tours.filter(tour=>tour.projectId===preview.projectId)} initialId={preview.tourId} initialSceneId={preview.sceneId} onClose={()=>setPreview(null)}/> }
    {usageProject&&<ProjectUsageDialog projectId={usageProject} onClose={()=>setUsageProject(null)}/>}
    {settings&&<Dialog title={settings.kind==="branding"?"اسم المشروع وشعاره":"ربط المشروع بالأنظمة الأخرى"} onClose={()=>setSettings(null)} wide={settings.kind==="api"}><div className="imo-form imo-settings-project"><label>المشروع<select value={settings.projectId} onChange={event=>setSettings({...settings,projectId:event.target.value})}>{data.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label></div>{settings.kind==="branding"?<BrandingEditor key={settings.projectId} projectId={settings.projectId} onError={setError} onSaved={()=>{setNotice("تم حفظ الاسم والشعار لجميع جولات المشروع.");setSettings(null);}}/>:<IntegrationKeys key={settings.projectId} projectId={settings.projectId} onError={setError}/>}</Dialog>}
  </main>;
}
function Brand(){return <div className="imo-wordmark dark"><span>IMO<span className="imo-logo-dot"/>3D</span><small>BY BMK SOLUTIONS</small></div>;}
type EditorProps={initial:Tour;onChange:(tour:Tour)=>void;onBack:()=>void;onError:(error:string)=>void;onNotice:(text:string)=>void;onBlockedChange:(blocked:boolean)=>void;onSettings:(kind:"branding"|"api"|"project")=>void;onDelete:(tour:Tour)=>void;onPreview:(tour:Tour,sceneId?:string)=>void};
type UploadFailure={file:File;message:string};
const editSnapshot=(tour:Tour)=>JSON.stringify({title:tour.title,published:tour.published,unit:tour.unit,scenes:tour.scenes.map(({id,name,room,floor})=>({id,name,room,floor})).sort((a,b)=>a.id.localeCompare(b.id))});
function Editor({initial,onChange,onBack,onError,onNotice,onBlockedChange,onSettings,onDelete,onPreview}:EditorProps){
  const [tour,setTour]=useState(initial),[tab,setTab]=useState<"scenes"|"links"|"plan"|"unit">("scenes"),[working,setWorking]=useState(false);
  const [uploadFloor,setUploadFloor]=useState(initial.scenes[0]?.floor??0);
  const [floorDirty,setFloorDirty]=useState(false),[boundaries,setBoundaries]=useState(false);
  const boundariesRef=useRef(false);
  const [progress,setProgress]=useState({done:0,total:0}),[failures,setFailures]=useState<UploadFailure[]>([]);
  const [dirty,setDirty]=useState(false),[floor,setFloor]=useState(initial.plans[0]?.floor??0),[publish,setPublish]=useState(false),[ruler,setRuler]=useState(false);
  const [sceneRemoval,setSceneRemoval]=useState<Scene|null>(null),[deletionError,setDeletionError]=useState("");
  const [job,setJob]=useState<ProcessingJob|null>(null),[jobLoading,setJobLoading]=useState(true),[jobError,setJobError]=useState(""),[resultWaiting,setResultWaiting]=useState(false);
  const images=useRef<HTMLInputElement>(null),cameras=useRef<HTMLInputElement>(null),active=useRef(true);
  const tourRef=useRef(initial),baseline=useRef(initial),dirtyRef=useRef(false),workingRef=useRef(false),jobRef=useRef<ProcessingJob|null>(null),jobVersion=useRef(0);
  const callbacks=useRef({onChange,onError,onNotice}),acceptRef=useRef<(value:Tour)=>void>(()=>{});
  const accept=(value:Tour)=>{tourRef.current=value;baseline.current=value;dirtyRef.current=false;setTour(value);setDirty(false);setFloorDirty(false);setFloor(previous=>value.plans.some(plan=>plan.floor===previous)?previous:value.plans[0]?.floor??0);callbacks.current.onChange(value);};
  useEffect(()=>{callbacks.current={onChange,onError,onNotice};acceptRef.current=accept;});
  useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
  useEffect(()=>{boundariesRef.current=boundaries;onBlockedChange(dirty||working||boundaries);return()=>onBlockedChange(false);},[dirty,working,boundaries,onBlockedChange]);
  useEffect(()=>{if(!dirty&&!working)return;const before=(event:BeforeUnloadEvent)=>{event.preventDefault();};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[dirty,working]);
  useEffect(()=>{
    let stopped=false,timer:ReturnType<typeof setTimeout>|undefined,lastApplied="";
    const abort=new AbortController();
    const poll=async()=>{
      let delay=8000;
      try{
        const version=jobVersion.current;
        const next=await api<ProcessingJob|null>(`tours/${initial.id}/processing`,{signal:abort.signal});
        if(version!==jobVersion.current){if(!stopped)timer=setTimeout(()=>void poll(),1500);return;}
        if(stopped)return;jobRef.current=next;setJob(next);setJobLoading(false);setJobError("");
        if(processingActive(next))delay=1500;
        else if(next){
          const key=`${next.id}:${next.status}:${next.updatedAt}`;
          if(lastApplied!==key){
            if(dirtyRef.current||workingRef.current||boundariesRef.current){setResultWaiting(true);delay=2000;}
            else{
              const latest=await api<Tour>(`tours/${initial.id}`,{signal:abort.signal});
              if(stopped)return;
              if(version!==jobVersion.current||latest.revision<tourRef.current.revision){delay=1500;}
              else if(dirtyRef.current||workingRef.current||boundariesRef.current){setResultWaiting(true);delay=2000;}
              else{acceptRef.current(latest);lastApplied=key;setResultWaiting(false);}
            }
          }
        }
      }catch(error){if(!stopped){setJobLoading(false);setJobError(error instanceof Error?error.message:"تعذر تحديث حالة المعالجة.");delay=4000;}}
      if(!stopped)timer=setTimeout(()=>void poll(),delay);
    };
    void poll();return()=>{stopped=true;abort.abort();if(timer)clearTimeout(timer);};
  },[initial.id]);
  const run=async(action:()=>Promise<void>)=>{if(workingRef.current)return;workingRef.current=true;setWorking(true);onError("");try{await action();}catch(error){if(active.current)onError(error instanceof Error?error.message:"تعذر تنفيذ العملية");}finally{workingRef.current=false;if(active.current){setWorking(false);setProgress({done:0,total:0});}}};
  const save=async(published=tourRef.current.published)=>{
    const draft=tourRef.current;
    const latest=await api<Tour>(`tours/${draft.id}`);
    if(latest.revision!==baseline.current.revision&&editSnapshot(latest)!==editSnapshot(baseline.current))throw Error("تغيّرت بيانات الجولة في نافذة أخرى. تعديلاتك ما زالت محفوظة في المحرر؛ افتح النسخة الأخرى لمراجعة التعارض قبل الحفظ.");
    const updated=await api<Tour>(`tours/${draft.id}`,{method:"PATCH",body:JSON.stringify({revision:latest.revision,title:draft.title,published,unit:draft.unit,scenes:draft.scenes.map(({id,name,room,floor})=>({id,name,room,floor}))})});
    if(active.current)accept(updated);return updated;
  };
  const edit=(value:Tour)=>{if(workingRef.current)return;tourRef.current=value;dirtyRef.current=true;setTour(value);setDirty(true);setFloorDirty(value.scenes.some(scene=>scene.floor!==baseline.current.scenes.find(item=>item.id===scene.id)?.floor));};
  const setProcessing=(next:ProcessingJob|null)=>{jobVersion.current++;jobRef.current=next;setJob(next);setJobLoading(false);};
  const startProcessing=async(value=tourRef.current)=>{
    if(value.scenes.length<2||value.scenes.length>300)throw Error("تحتاج المعالجة التلقائية إلى صورتين متداخلتين على الأقل، وبحد أقصى 300 صورة في الجولة.");
    const next=await api<ProcessingJob>(`tours/${value.id}/processing`,{method:"POST"});
    if(active.current){setProcessing(next);setJobError("");onNotice("بدأ تحليل الصور وربطها. يمكنك مغادرة الاستوديو؛ ستستمر المعالجة وتظهر النتيجة عند العودة.");}
  };
  const upload=async(files:FileList|File[]|null)=>{
    if(!files?.length)return;const list=Array.from(files),failed:UploadFailure[]=[];
    if(tourRef.current.scenes.length+list.length>300){onNotice("المعالجة التلقائية تدعم حتى 300 صورة لكل جولة. يمكنك تقسيم المشروع إلى جولات؛ ما يزيد عن ذلك يحتاج استيراد كاميرات بدل التحليل التلقائي.");}
    await run(async()=>{
      if(dirtyRef.current)await save();
      if(processingActive(jobRef.current))setProcessing(await api<ProcessingJob|null>(`tours/${tourRef.current.id}/processing-cancel`,{method:"POST"}));
      setFailures([]);setProgress({done:0,total:list.length});let uploaded=0;
      for(let index=0;index<list.length;index++){
        if(!active.current)break;
        try{if(list[index].size>100*1024*1024)throw Error("الحد الأقصى للصورة 100 ميجابايت.");const updated=await uploadPanorama(tourRef.current,list[index],uploadFloor);if(active.current)accept(updated);uploaded++;}
        catch(error){failed.push({file:list[index],message:error instanceof Error?error.message:"فشل الرفع"});}
        if(active.current)setProgress({done:index+1,total:list.length});
      }
      if(!active.current)return;setFailures(failed);
      // Photo analysis starts explicitly after the administrator finishes uploading.
      // Do not consume subscription usage after every partial upload batch.
      if(uploaded&&tourRef.current.scenes.length>=2&&tourRef.current.scenes.length<=300)await startProcessing();
      else if(uploaded)onNotice(tourRef.current.scenes.length<2?"تم حفظ اللقطة. أضف لقطة متداخلة أخرى لبدء الربط تلقائيًا.":"تم حفظ الصور. المعالجة البصرية متاحة للجولات حتى 300 لقطة؛ يمكن استيراد الكاميرات والعمق لهذه الجولة.");
      if(failed.length)onError(`تعذر رفع ${number(failed.length)} ملفات. اللقطات الناجحة محفوظة؛ يمكنك إعادة محاولة الملفات الموضحة أدناه.`);
    });
  };
  const processing=processingActive(job),link=`/imo3d/t/${tour.id}`;
  const estimated=tour.spatialSource==="images";
  const mapCount=tour.plans.filter(plan=>plan.architectureReview==="reviewed"&&!!plan.architecture).length;
  return <div className="imo-page imo-editor">
    <div className="imo-editor-heading"><div><button className="imo-back" disabled={working} onClick={()=>{if(dirty){onError("احفظ تعديلاتك قبل العودة إلى المشاريع.");return;}onBack();}}>المشاريع <span>/</span></button><input aria-label="اسم الجولة" value={tour.title} disabled={working} onChange={event=>edit({...tourRef.current,title:event.target.value})} maxLength={120}/><p>{tour.published?"متاحة عبر الرابط":"مسودة خاصة بالإدارة"} <i/> {dirty?"تعديلات غير محفوظة":`آخر حفظ ${new Date(tour.updatedAt).toLocaleTimeString("ar-SA",{hour:"2-digit",minute:"2-digit"})}`}</p></div><div className="imo-editor-actions"><button className="imo-button danger-outline" disabled={working} onClick={()=>onDelete(tourRef.current)}><Icon name="trash" size={17}/>حذف الجولة</button><button className="imo-button secondary" disabled={working||!tour.scenes.length} onClick={()=>void run(async()=>{if(dirtyRef.current)await save();onPreview(tourRef.current);})}><Icon name="eye"/>معاينة الجولة</button><button className="imo-button primary" disabled={working||!dirty} onClick={()=>void run(async()=>{await save();onNotice("تم حفظ التعديلات.");})}>{working?"جارٍ العمل…":"حفظ التعديلات"}</button></div></div>
    <div className="imo-workflow"><div className={tour.scenes.length?"done":""}><b>01</b><span>رفع اللقطات<small>{number(tour.scenes.length)} لقطة</small></span></div><div className={tour.quality.positioned===tour.scenes.length&&tour.scenes.length?"done":""}><b>02</b><span>الربط المكاني<small>{processing?"جارٍ تحليل الصور":`${number(tour.quality.positioned)} ${estimated?"مواضع مقدّرة":"مواضع كاميرا"}`}</small></span></div><div className={mapCount?"done":""}><b>03</b><span>{estimated?"مخطط المواقع":"مخطط الشقة"}<small>{number(mapCount)} مخططات</small></span></div><div className={tour.published?"done":""}><b>04</b><span>العرض والمشاركة<small>{tour.published?"الرابط متاح":"جاهز للمعاينة"}</small></span></div></div>
    <div className="imo-editor-project-tools"><span><Icon name="folder" size={17}/>إعدادات المشروع</span><button type="button" disabled={working} onClick={()=>onSettings("project")}>إدارة المشروع</button><button type="button" disabled={working} onClick={()=>onSettings("branding")}>الاسم والشعار</button><button type="button" disabled={working} onClick={()=>onSettings("api")}>مفاتيح API والتكامل</button></div>
    {job&&<section className={`imo-processing-card ${processing?"is-active":job.status}`} aria-label="حالة معالجة الصور"><div className="imo-processing-heading"><div>{processing?<span className="imo-spinner"/>:<Icon name={job.status==="completed"?"check":"info"} size={23}/>}<div><strong>{job.stage}</strong><small>{processing?"تستمر المعالجة حتى بعد إغلاق الصفحة.":job.result?`${number(job.result.registered)} / ${number(job.result.total)} لقطات ذات مواقع مقدّرة · ${number(job.result.links)} علاقات بصرية${job.result.rooms?` · حدود ${number(job.result.rooms)} فراغات`:""}`:"آخر عملية معالجة لهذه الجولة"}</small></div></div><span className="imo-processing-percent">{number(job.progress)}%</span></div><progress max={100} value={job.progress} aria-label="تقدم معالجة الصور"/>{job.error&&<p className="imo-error" role="alert">{job.error}</p>}{job.warnings.length>0&&!processing&&<details><summary>ملاحظات جودة النتيجة</summary>{job.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</details>}{resultWaiting&&<p className="imo-processing-waiting">نتيجة المعالجة جاهزة. احفظ تعديلات الأسماء والبيانات لإظهار النتيجة الجديدة دون فقدانها.</p>}<div className="imo-processing-actions">{processing?<button disabled={working} type="button" className="imo-button secondary" onClick={()=>void run(async()=>{setProcessing(await api<ProcessingJob|null>(`tours/${tour.id}/processing-cancel`,{method:"POST"}));onNotice("أُلغيت المعالجة. صورك وتعديلاتك محفوظة.");})}>إلغاء المعالجة</button>:<button disabled={working||tour.scenes.length<2||tour.scenes.length>300} type="button" className="imo-button secondary" onClick={()=>void run(async()=>{if(dirtyRef.current)await save();await startProcessing();})}>{["failed","cancelled","stale"].includes(job.status)?"إعادة المحاولة":"إعادة تحليل الصور"}</button>}{!processing&&tour.plans.some(plan=>plan.kind!=="missing")&&<button type="button" className="imo-button secondary" onClick={()=>setTab("plan")}>عرض المخطط</button>}</div></section>}
    {jobError&&<p className="imo-inline-alert" role="status">{jobError} ستُعاد محاولة الاتصال تلقائيًا؛ لا تبدأ عملية أخرى.</p>}
    <div className="imo-editor-layout"><section className="imo-editor-main"><div className="imo-tabs" role="tablist" aria-label="إعدادات الجولة">{([['scenes','اللقطات والغرف'],['links','الربط اليدوي'],['plan','مخطط الشقة'],['unit','بيانات الوحدة']] as const).map(([key,label])=><button role="tab" aria-selected={tab===key} key={key} disabled={working} onClick={()=>{if(key==="links"&&dirtyRef.current)void run(async()=>{await save();setTab(key);});else setTab(key);}}>{label}</button>)}</div>
      {tab==="scenes"&&<><div className="imo-dropzone" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!working)void upload(event.dataTransfer.files);}}><div className="imo-upload-symbol"><Icon name="upload" size={26}/></div><div><h3>ارفع الصور، ودع الربط يبدأ</h3><p>اختر لقطات 360 متداخلة؛ يبدأ تحليلها مع انتهاء الدفعة.</p><small>JPG، PNG، WEBP · بانوراما 2:1 · حتى 100 MiB للصورة</small><small>حتى 300 صورة للتحليل التلقائي في الجولة. يمكن حفظ حتى 500 صورة مع الربط اليدوي أو بيانات الكاميرات.</small><FloorSelector value={uploadFloor} floors={tour.scenes.map(scene=>scene.floor)} onChange={setUploadFloor} disabled={working} label="دور الصور الجديدة"/></div><button className="imo-button secondary" disabled={working||jobLoading} onClick={()=>images.current?.click()}>اختيار الصور</button><input ref={images} type="file" hidden multiple accept="image/jpeg,image/png,image/webp" onChange={event=>{void upload(event.target.files);event.target.value="";}}/></div>
      {working&&progress.total>0&&<div className="imo-upload-progress" role="status"><progress value={progress.done} max={progress.total}/><span>{number(progress.done)} / {number(progress.total)} لقطات</span></div>}
      {failures.length>0&&<div className="imo-upload-failures"><strong>ملفات تحتاج إعادة محاولة</strong><ul>{failures.map(({file,message},index)=><li key={`${file.name}-${index}`}><b>{file.name}</b><span>{message}</span></li>)}</ul><button type="button" disabled={working} className="imo-button secondary" onClick={()=>void upload(failures.map(failure=>failure.file))}>إعادة رفع الملفات الفاشلة</button></div>}
      {floorDirty&&<p className="imo-inline-alert">نقل صورة إلى دور آخر يزيل موضعها القديم وروابطها غير المتوافقة. احفظ التعديلات ثم أعد تحليل الصور لتحديد موقعها الصحيح.</p>}
      {tour.scenes.length?<div className="imo-scene-grid">{tour.scenes.map((scene,index)=><div className="imo-scene-card" key={scene.id}><div><img src={scene.thumbnail} alt={`بانوراما ${scene.name}`} loading="lazy"/><span>{String(index+1).padStart(2,"0")}</span><button className="imo-scene-delete" disabled={working} title="حذف الصورة" aria-label={`حذف صورة ${scene.sourceName}`} onClick={()=>{setSceneRemoval(scene);setDeletionError("");}}><Icon name="trash" size={18}/></button></div><input aria-label={`اسم غرفة اللقطة ${index+1}`} disabled={working} value={scene.room} onChange={event=>edit({...tourRef.current,scenes:tourRef.current.scenes.map(item=>item.id===scene.id?{...item,room:event.target.value,name:event.target.value}:item)})} maxLength={100}/><small title={scene.sourceName}>{scene.sourceName}</small><FloorSelector value={scene.floor} floors={tour.scenes.map(item=>item.floor)} disabled={working} label={`دور اللقطة ${index+1}`} onChange={next=>edit({...tourRef.current,scenes:tourRef.current.scenes.map(item=>item.id===scene.id?{...item,floor:next}:item)})}/><div className="imo-scene-status"><span className={scene.position?"yes":""}>{scene.position?estimated?"موقع مقدّر":"موقع معاير":"بانتظار المعالجة"}</span><span>{scene.depth?"عمق متوفر":`${number(scene.links.length)} روابط`}</span></div></div>)}</div>:<div className="imo-empty small"><p>ارفع صورتين متداخلتين على الأقل. يمكنك تعديل أسماء الغرف بعد الرفع.</p></div>}</>}
      {tab==="scenes"&&<SemanticRoomsEditor tour={tour} disabled={working||dirty} onChange={accept} onError={onError} onNotice={onNotice} onBusyChange={value=>{workingRef.current=value;setWorking(value);}}/>}
      {tab==="links"&&<ManualLinkEditor tour={tour} disabled={working||dirty} onChange={updated=>{accept(updated);setProcessing(null);}} onError={onError} onNotice={onNotice} onBusyChange={value=>{workingRef.current=value;setWorking(value);}}/>}
      {tab==="plan"&&<><AIPlanPanel tourId={tour.id} sceneCount={tour.scenes.length} disabled={working||dirty}/><ArchitectureReviewControls tour={tour} floor={floor} disabled={working||dirty} onSaved={updated=>{accept(updated);setProcessing(null);onNotice("تم اعتماد النموذج المعماري للعرض.");}} onError={onError}/><div className="imo-section-heading"><div><strong>مخطط خاص بهذه الشقة</strong><p className="imo-muted">حدود هذا الدور محفوظة داخل هذه الجولة وحدها.</p></div><button className="imo-button secondary" disabled={working} onClick={()=>void run(async()=>{if(dirtyRef.current)await save();boundariesRef.current=true;setBoundaries(true);})}>المحرر المعماري — جدران وأبواب ونوافذ</button></div>{estimated&&<div className="imo-estimated-plan-note"><Icon name="info" size={19}/><p>مخطط مواقع مقدّر من الصور بمقياس نسبي. يوضح ترتيب اللقطات وعلاقاتها؛ لا يمثل حدودًا معمارية أو أبعادًا بالمتر.</p></div>}<div className="imo-floor-tabs">{tour.plans.map(plan=><button className={plan.floor===floor?"selected":""} key={plan.floor} onClick={()=>setFloor(plan.floor)}>{plan.label}</button>)}</div>{tour.plans.find(plan=>plan.floor===floor)?<InteractiveFloorPlan allowDraft tourTitle={tour.title} spatialScale={tour.spatialScale} onMeasure={()=>setRuler(true)} plan={tour.plans.find(plan=>plan.floor===floor)!} scenes={tour.scenes} current={tour.scenes.find(scene=>scene.floor===floor)?.id??""} yaw={0} onSelect={id=>{const scene=tour.scenes.find(item=>item.id===id);if(scene)void run(async()=>{if(dirtyRef.current)await save();onPreview(tourRef.current,scene.id);});}}/>:<div className="imo-empty"><Icon name="map" size={40}/><h3>{processing?"جارٍ تحليل المكان":"المخطط بانتظار الصور"}</h3><p>ارفع صورًا متداخلة للمعالجة التلقائية، أو استورد بيانات الكاميرات والعمق.</p></div>}</>}
      {tab==="unit"&&<div className="imo-form imo-unit-editor"><label>رمز الوحدة<input disabled={working} value={tour.unit.code} maxLength={80} onChange={event=>edit({...tourRef.current,unit:{...tourRef.current.unit,code:event.target.value}})}/></label><div className="imo-two-cols">{([['price','السعر — ر.س'],['area','المساحة — م²'],['bedrooms','غرف النوم'],['bathrooms','دورات المياه']] as const).map(([key,label])=><label key={key}>{label}<input disabled={working} type="number" min={key==="area"?0.1:0} step={key==="area"?0.1:1} value={tour.unit[key]??""} onChange={event=>edit({...tourRef.current,unit:{...tourRef.current.unit,[key]:event.target.value===""?null:Number(event.target.value)}})}/></label>)}</div><p className="imo-muted">تظهر هذه المعلومات في الجولة وفي نموذج تسجيل الاهتمام.</p></div>}
    </section><aside className="imo-editor-side"><section><div className="imo-side-title"><Icon name="link"/><h3>الربط التلقائي من الصور</h3></div><p>يبحث المحرك عن التداخل بين اللقطات ويقدّر مواقعها، ثم ينشئ مخطط مواقع تلقائيًا.</p><button disabled={working||processing||jobLoading||tour.scenes.length<2||tour.scenes.length>300} className="imo-button primary full" onClick={()=>void run(async()=>{if(dirtyRef.current)await save();await startProcessing();})}>{processing?"المعالجة قيد التنفيذ":"تحليل الصور والبيانات المكانية"}</button><button disabled={working||tour.scenes.length<2} className="imo-button secondary full" onClick={()=>void run(async()=>{if(dirtyRef.current)await save();setTab("links");})}><Icon name="link" size={17}/>ربط الصور يدويًا</button><dl className="imo-quality"><div><dt>مواقع الكاميرات</dt><dd>{number(tour.quality.positioned)} / {number(tour.scenes.length)}</dd></div><div><dt>مجموعات متصلة</dt><dd>{number(tour.quality.components)}</dd></div><div><dt>لقطات ذات عمق</dt><dd>{number(tour.quality.depthScenes)}</dd></div></dl><p className="imo-quality-note">أفضل نتيجة تتطلب لقطات متداخلة على مستوى ثابت. العلاقة البصرية لا تثبت خلو المسار من الحواجز؛ النتائج غير المعايرة تحتاج مراجعة.</p>{tour.quality.warnings.length>0&&<details className="imo-import-help"><summary>مراجعة جودة الجولة</summary>{tour.quality.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</details>}</section>
      <section><div className="imo-side-title"><Icon name="layers"/><h3>كاميرات وعمق معاير</h3></div><p>لاستيراد بيانات مكانية معايرة بالمتر، أضف مواقع الكاميرات والعمق الشعاعي من مصدر معاير.</p><button disabled={working||processing} className="imo-button secondary full" onClick={()=>cameras.current?.click()}><Icon name="upload" size={18}/>استيراد الكاميرات والعمق</button><input type="file" accept="application/json,.json" hidden ref={cameras} onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;void run(async()=>{if(file.size>24_000_000)throw Error("ملف الكاميرات أكبر من 24 ميجابايت");if(dirtyRef.current)await save();const body=await file.text();JSON.parse(body);accept(await api<Tour>(`tours/${tour.id}/cameras`,{method:"POST",body}));onNotice("تمت مطابقة الكاميرات وتحديث الربط والمخطط.");});}}/><button disabled={working||processing||!tour.quality.depthScenes} className="imo-button secondary full" onClick={()=>void run(async()=>{if(dirtyRef.current)await save();accept(await api<Tour>(`tours/${tour.id}/rebuild`,{method:"POST"}));onNotice("تم تحديث الروابط والمخطط من بيانات العمق.");})}>إعادة البناء من العمق</button><details className="imo-import-help"><summary>صيغة ملف الكاميرات</summary><p>ملف JSON بالإصدار 1 ووحدة meters. لكل كاميرا: file، position (x,y,z)، yaw بالدرجات، floor، وroom اختياري. العمق شعاعي بالمتر بصيغة width، height، values.</p><p>إحداثيات X يمين، Y أعلى، والاتجاه صفر نحو −Z. يجب أن يطابق اسم الملف الصورة المرفوعة.</p></details></section>
      <section><div className="imo-side-title"><Icon name="eye"/><h3>رابط الجولة</h3></div><p>المسودة مرئية للإدارة فقط. إتاحة الرابط تسمح لأي شخص يملكه بمشاهدة الجولة.</p><button disabled={working||!tour.scenes.length} className="imo-button secondary full" onClick={()=>setPublish(true)}>{tour.published?"إدارة إتاحة الرابط":"إتاحة رابط المشاهدة"}</button>{tour.published&&<><button className="imo-button secondary full" onClick={()=>{navigator.clipboard.writeText(new URL(link,window.location.origin).href).then(()=>onNotice("تم نسخ رابط الجولة.")).catch(()=>onError("تعذر نسخ الرابط. اسمح للمتصفح باستخدام الحافظة ثم أعد المحاولة."));}}><Icon name="link" size={18}/>نسخ الرابط</button><button disabled={working} className="imo-button secondary full" onClick={()=>void run(async()=>{const embed=await api<{html:string}>(`tours/${tour.id}/embed`);await navigator.clipboard.writeText(embed.html);onNotice("تم نسخ كود التضمين لموقعك.");})}>نسخ كود التضمين</button></>}</section>
    </aside></div>
    {boundaries&&<ArchitecturalPlanEditor key={tour.revision+":"+floor} tour={tour} floor={floor} onClose={()=>{boundariesRef.current=false;setBoundaries(false);}} onSaved={updated=>{accept(updated);setProcessing(null);onNotice("حُفظت المسودة المعمارية. عرضا 2D و3D يستخدمان العناصر نفسها، وتحتاج إلى اعتماد قبل عرضها للعميل.");}}/>}
    {ruler&&tour.scenes[0]&&<MeasurementDialog key={tour.revision} plans={tour.plans} scenes={tour.scenes} initialFloor={floor} current={tour.scenes.find(scene=>scene.floor===floor)||tour.scenes[0]} spatialScale={tour.spatialScale} onClose={()=>setRuler(false)}/>}
    {sceneRemoval&&<Dialog title="حذف الصورة" onClose={()=>{if(!working)setSceneRemoval(null);}}><div className="imo-scene-delete-preview"><img src={sceneRemoval.thumbnail} alt={sceneRemoval.name}/><div><strong>{sceneRemoval.room}</strong><small dir="auto">{sceneRemoval.sourceName}</small></div></div><p>ستُحذف هذه الصورة وروابط التنقل ونقطتها على المخطط. بقية الصور محفوظة. لا يمكن التراجع عن الحذف.</p>{tour.scenes.length===1&&<p className="imo-inline-alert">هذه آخر صورة؛ ستتحول الجولة إلى مسودة حتى تضيف صورًا جديدة.</p>}{processing&&<p className="imo-muted">ستتوقف المعالجة الجارية حتى لا تعيد ربط الصورة المحذوفة. يمكنك تحليل الصور المتبقية بعد الحذف.</p>}{dirty&&<p className="imo-muted">سنحفظ تعديلاتك الحالية قبل حذف الصورة.</p>}{deletionError&&<p className="imo-error" role="alert">{deletionError}</p>}<div className="imo-dialog-actions"><button className="imo-button danger" disabled={working} onClick={()=>void run(async()=>{setDeletionError("");try{if(dirtyRef.current)await save();const latest=await api<Tour>("tours/"+tourRef.current.id);if(editSnapshot(latest)!==editSnapshot(baseline.current))throw Error("تغيرت الجولة في نافذة أخرى. أغلق نافذة الحذف وأعد فتح الجولة قبل المحاولة.");const updated=await api<Tour&{cleanupWarning?:string}>("tours/"+tourRef.current.id+"/scenes/"+sceneRemoval.id,{method:"DELETE",body:JSON.stringify({revision:latest.revision})});accept(updated);setProcessing(null);setSceneRemoval(null);onNotice(updated.cleanupWarning||"تم حذف الصورة وروابطها من الجولة.");}catch(reason){setDeletionError(reason instanceof Error?reason.message:"تعذر حذف الصورة.");}})}>{working?"جارٍ الحذف…":"حذف الصورة نهائيًا"}</button><button className="imo-button secondary" disabled={working} onClick={()=>setSceneRemoval(null)}>إلغاء</button></div></Dialog>}
    {publish&&<Dialog title={tour.published?"إيقاف إتاحة الرابط":"إتاحة رابط المشاهدة"} onClose={()=>setPublish(false)}><p>{tour.published?"ستصبح الجولة خاصة بالإدارة، ولن يستطيع الزوار فتح رابطها.":"سيتمكن من يملك رابط الجولة من مشاهدة الصور والمخطط وبيانات الوحدة."}</p>{processing&&<p className="imo-muted">المعالجة ما زالت جارية؛ ستُحدّث نتيجتها الجولة عند اكتمالها.</p>}<div className="imo-dialog-actions"><button className="imo-button primary" disabled={working} onClick={()=>void run(async()=>{await save(!tour.published);setPublish(false);onNotice("تم تحديث إتاحة الجولة.");})}>{tour.published?"جعلها مسودة":"إتاحة الرابط"}</button><button className="imo-button secondary" disabled={working} onClick={()=>setPublish(false)}>إلغاء</button></div></Dialog>}
  </div>;
}

