'use client';
import {suiteLoginPath,withBasePath} from '@/lib/imo3d/base-path';
import {useEffect,useState} from 'react';
type Project={id:string;name:string};
export default function ConnectChatGPT(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[login,setLogin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const response=await fetch(withBasePath('/api/imo3d-chatgpt/authorize')+window.location.search);if(response.status===401)return {login:true,projects:[] as Project[]};const value=await response.json();if(!response.ok)throw Error(value.error);return {login:false,projects:value.projects as Project[]};}
 // The owner signs in once, in the studio suite; it returns him here with the same authorization request.
 useEffect(()=>{let active=true;void load().then(value=>{if(active){setProjects(value.projects);setLogin(value.login);if(value.login)window.location.replace(suiteLoginPath(window.location.pathname+window.location.search));}}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;};},[]);
 return <main className="imo-shell imo-load" dir="rtl"><section className="imo-form" style={{width:'min(520px,92vw)',textAlign:'start',padding:24}}><h1>ربط IMO 3D مع ChatGPT</h1><p>اسمح لـChatGPT بقراءة صور مشروع واحد وتحليلها وحفظ مسودات مخططات منفصلة. لا يملك هذا الربط أدوات حذف المشاريع أو تغيير المخططات المعتمدة.</p>
 {login?<div className="imo-form"><p>سجّل الدخول بحساب استوديو BMK أولًا، ثم تعود إلى هذه الصفحة.</p><a className="imo-button primary" href={suiteLoginPath(window.location.pathname+window.location.search)}>الدخول إلى الاستوديو</a></div>:<form className="imo-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(withBasePath('/api/imo3d-chatgpt/authorize'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({authorization:Object.fromEntries(new URLSearchParams(window.location.search)),projectId})});const data=await response.json();if(!response.ok)throw Error(data.error);window.location.assign(data.redirect);}catch(error){setError(error instanceof Error?error.message:'تعذر الربط');setBusy(false);}}}><label>المشروع المسموح<select value={projectId} onChange={event=>setProjectId(event.target.value)} required disabled={busy}><option value="">اختر المشروع</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><p>ستصل صور المشروع إلى ChatGPT عند استخدام أدوات التحليل في المحادثة. يمكنك إلغاء الوصول من إعدادات IMO 3D.</p><button className="imo-button primary" disabled={busy||!projectId}>السماح بالربط لهذا المشروع</button></form>}
 {error&&<p role="alert" className="imo-error">{error}</p>}<a href={withBasePath('/')}>العودة إلى الإدارة</a></section></main>;
}
