'use client';
import {PasswordInput} from '@/components/imo3d/PasswordInput';
import {useEffect,useState} from 'react';
type Project={id:string;name:string};
export default function ConnectChatGPT(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[login,setLogin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const response=await fetch('/api/imo3d-chatgpt/authorize'+window.location.search);if(response.status===401)return {login:true,projects:[] as Project[]};const value=await response.json();if(!response.ok)throw Error(value.error);return {login:false,projects:value.projects as Project[]};}
 useEffect(()=>{let active=true;void load().then(value=>{if(active){setProjects(value.projects);setLogin(value.login);}}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;};},[]);
 return <main className="imo-shell imo-load" dir="rtl"><section className="imo-form" style={{width:'min(520px,92vw)',textAlign:'start',padding:24}}><h1>ربط IMO 3D مع ChatGPT</h1><p>اسمح لـChatGPT بقراءة صور مشروع واحد وتحليلها وحفظ مسودات مخططات منفصلة. لا يملك هذا الربط أدوات حذف المشاريع أو تغيير المخططات المعتمدة.</p>
 {login?<form className="imo-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{const password=String(new FormData(event.currentTarget).get('password'));const response=await fetch('/api/imo3d/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!response.ok)throw Error('تعذر الدخول. تحقق من كلمة مرور IMO 3D.');const value=await load();setProjects(value.projects);setLogin(value.login);}catch(error){setError(error instanceof Error?error.message:'تعذر الدخول');}finally{setBusy(false);}}}><label>كلمة مرور IMO 3D<PasswordInput name="password" autoComplete="current-password" required maxLength={256}/></label><button className="imo-button primary" disabled={busy}>دخول الإدارة</button></form>:<form className="imo-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/imo3d-chatgpt/authorize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({authorization:Object.fromEntries(new URLSearchParams(window.location.search)),projectId})});const data=await response.json();if(!response.ok)throw Error(data.error);window.location.assign(data.redirect);}catch(error){setError(error instanceof Error?error.message:'تعذر الربط');setBusy(false);}}}><label>المشروع المسموح<select value={projectId} onChange={event=>setProjectId(event.target.value)} required disabled={busy}><option value="">اختر المشروع</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><p>ستصل صور المشروع إلى ChatGPT عند استخدام أدوات التحليل في المحادثة. يمكنك إلغاء الوصول من إعدادات IMO 3D.</p><button className="imo-button primary" disabled={busy||!projectId}>السماح بالربط لهذا المشروع</button></form>}
 {error&&<p role="alert" className="imo-error">{error}</p>}<a href="/imo3d">العودة إلى الإدارة</a></section></main>;
}
